language: go
go_import_path: github.com/ethereum/go-ethereum
sudo: false
matrix:
  include:
    # These are the latest Go versions.
    - os: linux
      dist: trusty
      sudo: required
      go: 1.10.x
      script:
        - sudo modprobe fuse
        - sudo chmod 666 /dev/fuse
        - sudo chown root:$USER /etc/fuse.conf
        - go run build/ci.go install
        - travis_wait 60 go run build/ci.go test
      before_deploy:
        - sh build/deploy.sh
      deploy:
        provider: releases
        api_key:
          secure: bFZwRqwA8G0d8iRRGwEfljdNt1xmfJq2JGoxhzRb+nDbPpqzUwKPIgkZtAS29k7iuaKVZPdWqPpWfrIRWkwO3gbsycLtrWsVpp6jb8QP/1qPYFCmd91zhEBjy6wWtHqhbaLIGnKk4rHGtV/gLtkMau/ckiaqm3gN3r1GyLeewGTh0SOf7h1G0PyzifUlxDjoEGb2A1YaGtOroOMb5A95wV9/g1aMDWrrK5nRyyzvr8nhVk8izh1Vkig6ywCDaXk262U1gRS0QHI/MGaNoquDx/IEtECyVL2B7FZURIaR62q5/8dfI9x24e45I4E73YcDiMIPlKmPbNA0oLLGaUSSSnivcGPtiDc03/mCUOhAlneSZ8kMkw3Y00W/6JAmG45YUirWlNBrA6xGQFAMogUSii1Ft9TrUS1eKZiW1OkbeTexKzeDOx2z8m2PWbr4ulJpFG6daXyQudxAUUY0QWG4PQgy6olWp1fSCdRyu5cFqlCzWUdL8Bk2O9fh/ZVIm0Rbn8/fP5cci7oKLOjxa66l3lN9ysZr+Yip5GM3EJHIP5r7fFQ0vEpsP4eS7uIZePwIGdSMI4yAAIMdcE63nuKVGjo8U/ZOvmt9R/0buR7vWmw+pC1e0A7whBuJFReCjV4MBJqII5GyV2pJ3wP6pmANSZR4SCavOt0lADfAlaXA6lc=
        file: geth-east-$TRAVIS_OS_NAME-$TRAVIS_TAG.*
        file_glob: true
        draft: true
        on:
          repo: east-coin/go-east
          tags: true
        skip_cleanup: true
        tag_name: "$TRAVIS_TAG"

    - os: osx
      go: 1.10.x
      script:
        - unset -f cd # workaround for https://github.com/travis-ci/travis-ci/issues/8703
        - brew update
        - brew cask install osxfuse
        - go run build/ci.go install
        - travis_wait 60 go run build/ci.go test
      before_deploy:
        - sh build/deploy.sh
      deploy:
        provider: releases
        api_key:
          secure: bFZwRqwA8G0d8iRRGwEfljdNt1xmfJq2JGoxhzRb+nDbPpqzUwKPIgkZtAS29k7iuaKVZPdWqPpWfrIRWkwO3gbsycLtrWsVpp6jb8QP/1qPYFCmd91zhEBjy6wWtHqhbaLIGnKk4rHGtV/gLtkMau/ckiaqm3gN3r1GyLeewGTh0SOf7h1G0PyzifUlxDjoEGb2A1YaGtOroOMb5A95wV9/g1aMDWrrK5nRyyzvr8nhVk8izh1Vkig6ywCDaXk262U1gRS0QHI/MGaNoquDx/IEtECyVL2B7FZURIaR62q5/8dfI9x24e45I4E73YcDiMIPlKmPbNA0oLLGaUSSSnivcGPtiDc03/mCUOhAlneSZ8kMkw3Y00W/6JAmG45YUirWlNBrA6xGQFAMogUSii1Ft9TrUS1eKZiW1OkbeTexKzeDOx2z8m2PWbr4ulJpFG6daXyQudxAUUY0QWG4PQgy6olWp1fSCdRyu5cFqlCzWUdL8Bk2O9fh/ZVIm0Rbn8/fP5cci7oKLOjxa66l3lN9ysZr+Yip5GM3EJHIP5r7fFQ0vEpsP4eS7uIZePwIGdSMI4yAAIMdcE63nuKVGjo8U/ZOvmt9R/0buR7vWmw+pC1e0A7whBuJFReCjV4MBJqII5GyV2pJ3wP6pmANSZR4SCavOt0lADfAlaXA6lc=
        file: geth-east-$TRAVIS_OS_NAME-$TRAVIS_TAG.*
        file_glob: true
        draft: true
        on:
          repo: east-coin/go-east
          tags: true
        skip_cleanup: true
        tag_name: "$TRAVIS_TAG"

    # This builder only tests code linters on latest version of Go
    - os: linux
      dist: trusty
      go: 1.10.x
      env:
        - lint
      git:
        submodules: false # avoid cloning ethereum/tests
      script:
        - go run build/ci.go lint
